version: "3.8"
services:
    db:
        container_name: "mysql_be"
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=exampleX3
            - MYSQL_DATABASE=mysql_be_challenge
            - MYSQL_USER=dev3
            - MYSQL_PASSWORD=dev300
        ports:
            - 3306:3306
